# Generated by Django 3.2.5 on 2021-07-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airfoil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('geometry', models.JSONField(blank=True, null=True)),
                ('polar', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='[m]')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='[kg]')),
                ('root_diameter', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='[m]')),
                ('number_of_bolts', models.IntegerField()),
                ('bolt_hole_diameter', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='[mm]')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('density', models.FloatField(verbose_name='[kg/m^3]')),
                ('e_modulus', models.FloatField(verbose_name='Youngs Modulus')),
                ('yield_strength', models.FloatField(verbose_name='yield strength')),
                ('ultimate_strength', models.FloatField(verbose_name='ultimate strength')),
                ('property', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rated_power', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reted_torque', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gen_type', models.CharField(max_length=255)),
                ('efficiency', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pole_pairs', models.IntegerField()),
                ('image', models.ImageField(upload_to='generator')),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('airfoil', models.ManyToManyField(to='WindTurbine.Airfoil')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
