# Generated by Django 3.1.7 on 2021-03-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WindTurbine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rated_power', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reted_torque', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gen_type', models.CharField(max_length=255)),
                ('efficiency', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pole_pairs', models.IntegerField()),
            ],
        ),
    ]
