# Generated by Django 3.1.7 on 2021-04-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WindTurbine', '0002_auto_20210323_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='density',
            field=models.FloatField(default=0, verbose_name='[kg/m^3]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='e_modulus',
            field=models.FloatField(default=0, verbose_name='Youngs Modulus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='ultimate_strength',
            field=models.FloatField(default=0, verbose_name='ultimate strength'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='yield_strength',
            field=models.FloatField(default=0, verbose_name='yield strength'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blade',
            name='bolt_hole_diameter',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='[mm]'),
        ),
        migrations.AlterField(
            model_name='blade',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='[m]'),
        ),
        migrations.AlterField(
            model_name='blade',
            name='root_diameter',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='[m]'),
        ),
        migrations.AlterField(
            model_name='blade',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='[kg]'),
        ),
    ]
