# Generated by Django 3.1.7 on 2021-03-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WindTurbine', '0002_generator'),
    ]

    operations = [
        migrations.AddField(
            model_name='generator',
            name='image',
            field=models.ImageField(default=0, upload_to='generator'),
            preserve_default=False,
        ),
    ]
