# Generated by Django 3.1.6 on 2021-02-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WindTurbine', '0003_blade_airfoils'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blade',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='blade',
            name='airfoils',
        ),
        migrations.AddField(
            model_name='blade',
            name='airfoil',
            field=models.ManyToManyField(to='WindTurbine.Airfoil'),
        ),
    ]
